import SiteNavigation from './SiteNavigation';
import SiteFooter from './SiteFooter';

interface TermsPageProps {
  onNavigate: (page: string) => void;
  onShowAuth: () => void;
  onShowSignIn?: () => void;
}

export default function TermsPage({ onNavigate, onShowAuth, onShowSignIn }: TermsPageProps) {
  const lastUpdated = 'May 2026';

  return (
    <div className="min-h-screen bg-slate-900">
      <SiteNavigation onNavigate={onNavigate} onShowAuth={onShowAuth} onShowSignIn={onShowSignIn} />

      <section className="pt-32 pb-24 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <div className="mb-10">
            <h1 className="text-4xl font-bold text-white mb-3">Terms of Use</h1>
            <p className="text-gray-400">Last updated: {lastUpdated}</p>
          </div>

          {/* Important Disclaimer Banner */}
          <div className="bg-amber-500/10 border-2 border-amber-500/40 rounded-2xl p-6 mb-10">
            <h2 className="text-lg font-bold text-amber-300 mb-3 flex items-center gap-2">
              <span className="text-xl">⚠</span> Important Disclaimer — Please Read Carefully
            </h2>
            <p className="text-amber-100/80 leading-relaxed mb-3">
              All readings, calculations, interpretations, name correction suggestions, remedies, and any other information provided by the NumberTeller platform are generated entirely by automated, system-driven algorithms. These outputs are <strong className="text-amber-200">not</strong> the result of human expertise, psychic ability, verified spiritual knowledge, or any form of professional life, legal, medical, financial, or psychological advice.
            </p>
            <p className="text-amber-100/80 leading-relaxed mb-3">
              <strong className="text-amber-200">The results produced by this platform may be incomplete, partially incorrect, or entirely incorrect.</strong> Numerology is an interpretive practice and all outputs carry inherent uncertainty. No algorithm can fully replicate the nuanced judgement of an experienced human practitioner.
            </p>
            <p className="text-amber-100/80 leading-relaxed mb-3">
              All professional numerologists, practitioners, consultants, and users of this platform are <strong className="text-amber-200">strongly advised to independently verify and re-examine all calculations, interpretations, and suggestions</strong> produced by this platform before acting upon them or presenting them to any client or third party.
            </p>
            <p className="text-amber-100/80 leading-relaxed">
              <strong className="text-amber-200">This platform must be used for reference purposes only.</strong> It is a calculation tool to assist professional practitioners — not a substitute for expert human judgement. Confiex Data Room Private Limited expressly disclaims any and all liability for any decisions made, actions taken, or outcomes arising from reliance on information generated by this platform.
            </p>
          </div>

          <div className="prose prose-invert max-w-none space-y-8 text-gray-300 leading-relaxed">

            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using NumberTeller (the "Platform"), operated by Confiex Data Room Private Limited, a company registered in Mumbai, India ("Confiex", "we", "us", or "our"), you agree to be bound by these Terms of Use in their entirety. If you do not agree to these terms, you must not access or use the Platform.
              </p>
              <p>
                These Terms apply to all users of the Platform, including registered account holders and visitors who access the Platform without registering. Your continued use of the Platform following any modification to these Terms constitutes your acceptance of the revised Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. Platform Description and Intended Use</h2>
              <p>
                NumberTeller is a professional numerology software platform designed for use by practising numerologists, holistic consultants, life coaches, Vedic astrologers, and other professional practitioners. It provides calculation tools, AI-assisted name correction analysis, Lo Shu Grid analysis, compatibility scoring, transit chart calculations, chart management, PDF export, and related professional resources using Pythagorean numerology methodology.
              </p>
              <p>
                The Platform is a tool to assist professional practitioners in their work. It is not designed or intended for use by end consumers seeking personal numerological advice. Users must be professional practitioners who exercise independent professional judgement in all client interactions.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. Disclaimer of Accuracy and Reliability</h2>
              <p>
                All calculations, interpretations, name correction suggestions, life path analyses, compatibility scores, remedy recommendations, and any other outputs produced by this Platform (collectively, "Platform Outputs") are generated entirely by automated computational algorithms. Platform Outputs:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-400">
                <li>Are provided "as is" and "as computed" without any guarantee of accuracy, completeness, or fitness for any particular purpose</li>
                <li>May be partially or wholly incorrect, misleading, or inapplicable to any specific individual, situation, or context</li>
                <li>Do not constitute advice of any kind, including but not limited to life advice, spiritual guidance, legal advice, medical advice, financial advice, or psychological counselling</li>
                <li>Are generated by pattern-matching and mathematical reduction algorithms and do not incorporate human intuition, lived experience, or contextual judgement</li>
                <li>Should never be presented to any third party as definitive, infallible, or authoritative guidance</li>
              </ul>
              <p>
                <strong className="text-white">Practitioners are strongly advised to independently verify, cross-check, and exercise their own professional judgement with respect to every output produced by this Platform before using it in any client-facing context.</strong> The Platform is expressly intended as a reference and calculation tool only.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">4. No Professional Advice</h2>
              <p>
                Nothing produced by this Platform constitutes professional advice of any kind. The Platform does not provide:
              </p>
              <ul className="list-disc pl-6 space-y-1.5 text-gray-400">
                <li>Life, spiritual, or personal development advice</li>
                <li>Legal, regulatory, or compliance advice</li>
                <li>Medical, psychological, psychiatric, or mental health advice</li>
                <li>Financial, investment, or business strategy advice</li>
                <li>Relationship or therapeutic counselling</li>
              </ul>
              <p>
                Practitioners who use Platform Outputs as part of consultations with clients are solely responsible for the advice, guidance, and recommendations they provide. Confiex accepts no responsibility for any practitioner's advice to any client.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">5. Account Registration</h2>
              <p>To access the Platform's features, you must create an account. You agree to:</p>
              <ul className="list-disc pl-6 space-y-1.5 text-gray-400">
                <li>Provide accurate, current, and complete information during registration</li>
                <li>Maintain the security of your password — passwords must meet minimum strength requirements</li>
                <li>Accept all responsibility for all activity conducted under your account</li>
                <li>Notify us immediately of any unauthorised use of your account</li>
                <li>Not share your account credentials with any third party</li>
              </ul>
              <p>
                You must be at least 18 years of age to create an account. By registering, you represent that you are at least 18 years old and have the legal capacity to enter into these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">6. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-6 space-y-1.5 text-gray-400">
                <li>Use the Platform for any unlawful purpose or in violation of any applicable law or regulation</li>
                <li>Attempt to gain unauthorised access to any part of the Platform or its infrastructure</li>
                <li>Reverse engineer, decompile, or disassemble any part of the Platform</li>
                <li>Use automated scripts, bots, or scraping tools to access or interact with the Platform</li>
                <li>Reproduce, distribute, or create derivative works from Platform content without express written permission</li>
                <li>Use the Platform to process third-party personal data in violation of applicable privacy laws</li>
                <li>Resell, sublicence, or provide access to the Platform to third parties without authorisation</li>
                <li>Present Platform Outputs as the work or opinion of a licensed professional in any regulated field</li>
                <li>Make any representation to clients or third parties that Platform Outputs are guaranteed to be accurate or authoritative</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">7. Client Data and Practitioner Responsibility</h2>
              <p>
                As a practitioner, you may input data relating to your clients (including names, dates of birth, and other personal information) into the Platform. You represent and warrant that:
              </p>
              <ul className="list-disc pl-6 space-y-1.5 text-gray-400">
                <li>You have obtained all necessary consents from your clients to process their personal data using this Platform</li>
                <li>You comply with all applicable data protection laws in your jurisdiction</li>
                <li>You have informed your clients that any analysis is generated by automated algorithms and may not be accurate</li>
                <li>You bear sole responsibility for any advice, reading, or recommendation you deliver to your clients based on Platform Outputs</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">8. Intellectual Property</h2>
              <p>
                All content on the Platform — including but not limited to the calculation engine, AI name correction algorithms, interface design, text, graphics, and Platform Outputs — is the intellectual property of Confiex Data Room Private Limited and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written consent.
              </p>
              <p>
                You retain ownership of data you input into the Platform. By inputting data, you grant Confiex a limited licence to process that data solely to provide the Platform's services to you.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">9. Disclaimer of Warranties</h2>
              <p>
                THE PLATFORM IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT. CONFIEX DOES NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS. CONFIEX MAKES NO WARRANTY REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF ANY PLATFORM OUTPUTS.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">10. Limitation of Liability</h2>
              <p>
                TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, CONFIEX DATA ROOM PRIVATE LIMITED AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc pl-6 space-y-1.5 text-gray-400">
                <li>Any loss or damage arising from reliance on Platform Outputs</li>
                <li>Any loss arising from advice given to clients based on Platform Outputs</li>
                <li>Any loss of profits, data, business, reputation, or goodwill</li>
                <li>Any decisions made by practitioners or their clients based on Platform Outputs</li>
                <li>Any damages arising from access to or inability to access the Platform</li>
              </ul>
              <p>
                IN NO EVENT SHALL CONFIEX'S TOTAL CUMULATIVE LIABILITY TO YOU EXCEED THE TOTAL AMOUNT PAID BY YOU TO CONFIEX IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
              </p>
              <p>
                SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OF LIABILITY FOR CERTAIN TYPES OF DAMAGES. IN SUCH JURISDICTIONS, CONFIEX'S LIABILITY IS LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">11. Indemnification</h2>
              <p>
                You agree to indemnify, defend, and hold harmless Confiex Data Room Private Limited and its officers, directors, employees, and agents from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including legal fees) arising from: (a) your use of the Platform; (b) advice or services you provide to clients based on Platform Outputs; (c) your violation of these Terms; or (d) your violation of any third-party right, including privacy rights.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">12. Account Suspension and Termination</h2>
              <p>
                We reserve the right to suspend or terminate your account immediately and without notice for: violation of these Terms; fraudulent, abusive, or harmful activity; non-payment of subscription fees; or any other reason at our sole discretion. You may close your account at any time by contacting our support team.
              </p>
              <p>
                Upon termination, your right to access the Platform ceases immediately. Saved chart data will be retained for 30 days after account closure before permanent deletion, unless you request immediate deletion.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">13. Modifications to Terms and Platform</h2>
              <p>
                We may update these Terms at any time. We will notify registered users of material changes by email at least 14 days before the changes take effect. Continued use of the Platform after the effective date constitutes acceptance of the revised Terms. We also reserve the right to modify, suspend, or discontinue any aspect of the Platform at any time.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">14. Governing Law and Jurisdiction</h2>
              <p>
                These Terms of Use shall be governed by and construed exclusively in accordance with the laws of the Republic of India. Any dispute, controversy, or claim arising out of or in connection with these Terms, or the breach, termination, or invalidity thereof, shall be subject to the exclusive jurisdiction of the courts of Mumbai, India. You irrevocably submit to the personal jurisdiction of such courts and waive any objection to proceedings in such courts on grounds of venue or inconvenient forum.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">15. Severability</h2>
              <p>
                If any provision of these Terms is found to be invalid or unenforceable under applicable law, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remainder of these Terms shall continue in full force and effect.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">16. Entire Agreement</h2>
              <p>
                These Terms, together with our Privacy Policy and Billing Policy, constitute the entire agreement between you and Confiex with respect to your use of the Platform and supersede all prior agreements, representations, and understandings.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">17. Contact</h2>
              <p>For questions about these Terms, contact us at:</p>
              <div className="bg-slate-800 border border-white/10 rounded-xl p-5 mt-3">
                <p className="font-semibold text-white">Confiex Data Room Private Limited</p>
                <p>Unit 302, Bldg 2, New Sonal Industrial Estate, Kachpada, Link Road, Malad West, Mumbai 400064</p>
                <p>Phone / WhatsApp: <a href="tel:+917900075531" className="text-blue-400 hover:text-blue-300">+91 7900075531</a></p>
                <p>Email: <a href="mailto:legal@numberteller.com" className="text-blue-400 hover:text-blue-300">legal@numberteller.com</a></p>
              </div>
            </section>

          </div>
        </div>
      </section>

      <SiteFooter onNavigate={onNavigate} onShowAuth={onShowAuth} />
    </div>
  );
}
