import { jsPDF } from 'jspdf';
import { MISSING_NUMBER_REMEDIES, ELEMENT_REMEDIES } from '../data/loShuInterpretations';
import { NUMBER_INTERPRETATIONS } from '../data/interpretations';

// ─── Palette ──────────────────────────────────────────────────────────────────
const C = {
  navy:    '#0a1628',
  navy2:   '#0f2040',
  navy3:   '#162a52',
  teal:    '#0ea5e9',
  teal2:   '#38bdf8',
  gold:    '#f59e0b',
  gold2:   '#fbbf24',
  white:   '#ffffff',
  off:     '#e2e8f0',
  gray:    '#94a3b8',
  dgray:   '#475569',
  lgray:   '#cbd5e1',
  emerald: '#10b981',
  rose:    '#f43f5e',
  amber:   '#fb923c',
};

// ─── Helper ───────────────────────────────────────────────────────────────────
class PDF {
  doc: jsPDF;
  y: number;
  page: number;
  W: number;
  H: number;
  M: number;   // margin
  CW: number;  // content width
  planId: string;

  constructor(planId: string) {
    this.doc = new jsPDF({ unit: 'mm', format: 'a4' });
    this.y = 0;
    this.page = 0;
    this.W = 210;
    this.H = 297;
    this.M = 16;
    this.CW = 210 - 32;
    this.planId = planId;
  }

  rgb(hex: string): [number, number, number] {
    return [
      parseInt(hex.slice(1, 3), 16),
      parseInt(hex.slice(3, 5), 16),
      parseInt(hex.slice(5, 7), 16),
    ];
  }
  fill(c: string) { this.doc.setFillColor(...this.rgb(c)); }
  stroke(c: string) { this.doc.setDrawColor(...this.rgb(c)); }
  tc(c: string) { this.doc.setTextColor(...this.rgb(c)); }

  need(h: number) {
    if (this.y + h > this.H - 22) this.newPage();
  }

  newPage() {
    this.doc.addPage();
    this.page++;
    this._pageChrome();
    this.y = 28;
  }

  _pageChrome() {
    // Top bar
    this.fill(C.navy);
    this.doc.rect(0, 0, this.W, 12, 'F');
    // Teal accent strip
    this.fill(C.teal);
    this.doc.rect(0, 0, 2, 12, 'F');
    // Logo mark
    this.fill(C.teal);
    this.doc.roundedRect(this.M, 2.5, 7, 7, 1, 1, 'F');
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(6);
    this.doc.text('#', this.M + 2.5, 7.4);
    // Brand
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(7.5);
    this.doc.text('NumberTeller', this.M + 9, 7.4);
    // Separator dot
    this.tc(C.dgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(7);
    this.doc.text('·', this.M + 37, 7.4);
    this.tc(C.gray);
    this.doc.setFontSize(6.5);
    this.doc.text('Numerology Reading Report', this.M + 40, 7.4);
    // Page number (right)
    this.tc(C.gray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(6.5);
    this.doc.text(`Page ${this.page + 1}`, this.W - this.M, 7.4, { align: 'right' });
    // Bottom footer
    const fy = this.H - 8;
    this.fill(C.navy);
    this.doc.rect(0, fy - 4, this.W, 12, 'F');
    this.fill(C.teal);
    this.doc.rect(0, fy - 4, 2, 12, 'F');
    this.tc(C.dgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(6);
    this.doc.text(
      `Generated by NumberTeller  ·  www.numberteller.com  ·  ${_today()}`,
      this.W / 2, fy, { align: 'center' }
    );
  }

  // Cover page ─────────────────────────────────────────────────────────────────
  cover(name: string, birthDate: string, planLabel: string, numbers: { label: string; value: string | number }[]) {
    this.page = 0;

    // Full navy background
    this.fill(C.navy);
    this.doc.rect(0, 0, this.W, this.H, 'F');

    // Subtle top gradient strip
    this.fill(C.navy2);
    this.doc.rect(0, 0, this.W, 60, 'F');

    // Decorative teal band at top
    this.fill(C.teal);
    this.doc.rect(0, 0, this.W, 3, 'F');

    // Right-side geometric accent
    this.fill(C.navy3);
    this.doc.rect(140, 40, 70, 100, 'F');
    this.fill(C.teal);
    this.doc.rect(140, 40, 2, 100, 'F');

    // Logo block (top left)
    const lx = this.M, ly = 18;
    this.fill(C.teal);
    this.doc.roundedRect(lx, ly, 12, 12, 2, 2, 'F');
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.text('#', lx + 3.8, ly + 8.5);

    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(16);
    this.doc.text('NumberTeller', lx + 15, ly + 8.5);

    this.tc(C.teal2);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(7.5);
    this.doc.text('www.numberteller.com', lx + 15, ly + 13.5);

    // Thin divider
    this.stroke(C.navy3);
    this.doc.setLineWidth(0.4);
    this.doc.line(this.M, 42, 135, 42);

    // Report type label
    this.tc(C.teal);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.text('PERSONAL NUMEROLOGY READING', this.M, 54);

    // Subject name (large)
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(30);
    const nameLines = this.doc.splitTextToSize(name, 120);
    this.doc.text(nameLines[0], this.M, 68);
    if (nameLines[1]) {
      this.doc.setFontSize(22);
      this.doc.text(nameLines[1], this.M, 78);
    }

    // Birth date row
    this.tc(C.gray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10);
    this.doc.text('Date of Birth', this.M, 84);
    this.tc(C.lgray);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(10);
    this.doc.text(birthDate, this.M + 26, 84);

    // Plan badge
    const badgeColor = planLabel.toLowerCase().includes('expert') ? C.gold
                      : planLabel.toLowerCase().includes('calculator') ? C.teal
                      : C.emerald;
    this.fill(badgeColor);
    this.doc.roundedRect(this.M, 89, 38, 7, 1.5, 1.5, 'F');
    this.tc(C.navy);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(7);
    this.doc.text(planLabel.toUpperCase(), this.M + 19, 93.8, { align: 'center' });

    // ── Core Numbers Grid ──
    const gridTop = 108;
    const cols = Math.min(numbers.length, 6);
    const cellW = (this.CW) / cols;
    const cellH = 26;

    // Section label
    this.tc(C.teal);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(7.5);
    this.doc.text('CORE NUMBERS AT A GLANCE', this.M, gridTop - 5);
    this.stroke(C.teal);
    this.doc.setLineWidth(0.2);
    this.doc.line(this.M, gridTop - 3, this.M + 55, gridTop - 3);

    numbers.slice(0, cols).forEach((n, i) => {
      const cx = this.M + i * cellW;
      // Cell bg
      this.fill(C.navy2);
      this.doc.rect(cx, gridTop, cellW - 1.5, cellH, 'F');
      // Accent bar at top of cell
      this.fill(i === 0 ? C.teal : i === 1 ? C.gold : i === 2 ? C.emerald : C.dgray);
      this.doc.rect(cx, gridTop, cellW - 1.5, 1.5, 'F');
      // Number value
      this.tc(C.white);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setFontSize(18);
      this.doc.text(String(n.value), cx + (cellW - 1.5) / 2, gridTop + 13, { align: 'center' });
      // Label
      this.tc(C.gray);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(6);
      const lLines = this.doc.splitTextToSize(n.label, cellW - 4);
      this.doc.text(lLines[0], cx + (cellW - 1.5) / 2, gridTop + 20, { align: 'center' });
    });

    // ── Description block ──
    const descY = gridTop + cellH + 14;
    this.fill(C.navy2);
    this.doc.rect(this.M, descY, this.CW, 28, 'F');
    this.fill(C.teal);
    this.doc.rect(this.M, descY, 2, 28, 'F');
    this.tc(C.teal2);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.text('About This Report', this.M + 6, descY + 7);
    this.tc(C.lgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    const descText = 'This personalised numerology report has been generated using the Pythagorean system. It analyses your core numbers, life cycles, karmic patterns, and personal year energy to provide deep insight into your character, strengths, challenges, and life direction.';
    const descLines = this.doc.splitTextToSize(descText, this.CW - 12);
    this.doc.text(descLines, this.M + 6, descY + 14);

    // Bottom watermark & footer
    this.tc(C.navy2);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(80);
    this.doc.text('#', this.W + 5, this.H - 12, { align: 'right' });

    this.tc(C.dgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(6.5);
    this.doc.text(
      `Generated by NumberTeller  ·  www.numberteller.com  ·  ${_today()}`,
      this.W / 2, this.H - 7, { align: 'center' }
    );
  }

  // Section heading ────────────────────────────────────────────────────────────
  sectionHeading(title: string, color = C.teal) {
    this.need(16);
    this.fill(C.navy2);
    this.doc.rect(this.M, this.y, this.CW, 9, 'F');
    this.fill(color);
    this.doc.rect(this.M, this.y, 3, 9, 'F');
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.text(title.toUpperCase(), this.M + 7, this.y + 6);
    this.y += 13;
  }

  // Sub heading ────────────────────────────────────────────────────────────────
  subHeading(title: string, color = C.teal) {
    this.need(10);
    this.tc(color);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8.5);
    this.doc.text(title, this.M, this.y);
    this.y += 4.5;
    this.stroke(color);
    this.doc.setLineWidth(0.15);
    this.doc.line(this.M, this.y, this.M + Math.min(this.doc.getTextWidth(title) * 0.85, 80), this.y);
    this.y += 3.5;
  }

  // Interpretation card ────────────────────────────────────────────────────────
  numberCard(label: string, value: string | number, interp?: { traits: string[]; challenges: string[]; advice: string[] }) {
    const hasInterp = !!interp;
    const cardH = hasInterp ? 48 : 14;
    this.need(cardH + 4);

    // Background
    this.fill(C.navy2);
    this.doc.roundedRect(this.M, this.y, this.CW, cardH, 2, 2, 'F');

    // Left accent strip
    this.fill(C.teal);
    this.doc.roundedRect(this.M, this.y, 3, cardH, 2, 0, 'F');
    this.doc.rect(this.M + 1.5, this.y, 1.5, cardH, 'F');

    // Number badge
    const badgeR = 5.5;
    const badgeCX = this.M + 14;
    const badgeCY = this.y + (hasInterp ? 10 : 7);
    this.fill(C.teal);
    this.doc.circle(badgeCX, badgeCY, badgeR, 'F');
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.text(String(value), badgeCX, badgeCY + 1.5, { align: 'center' });

    // Label
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.text(label, this.M + 22, this.y + (hasInterp ? 7 : 8.5));

    if (hasInterp && interp) {
      const textX = this.M + 22;
      const maxW = this.CW - 28;

      // Traits
      this.tc(C.teal2);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setFontSize(7);
      this.doc.text('KEY TRAITS', textX, this.y + 14);
      this.tc(C.lgray);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(7.5);
      const traitsText = interp.traits.slice(0, 3).join('  ·  ');
      const traitLines = this.doc.splitTextToSize(traitsText, maxW);
      this.doc.text(traitLines.slice(0, 2), textX, this.y + 19);

      // Challenges
      this.tc(C.gold2);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setFontSize(7);
      this.doc.text('CHALLENGES', textX, this.y + 30);
      this.tc(C.lgray);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(7.5);
      const chalText = interp.challenges.slice(0, 2).join('  ·  ');
      const chalLines = this.doc.splitTextToSize(chalText, maxW);
      this.doc.text(chalLines[0], textX, this.y + 35);

      // Advice
      this.tc(C.emerald);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setFontSize(7);
      this.doc.text('GUIDANCE', textX, this.y + 42);
      this.tc(C.lgray);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(7.5);
      const advText = interp.advice.slice(0, 1).join('  ·  ');
      this.doc.text(advText, textX, this.y + 47);
    }

    this.y += cardH + 3;
  }

  // Key-value row ──────────────────────────────────────────────────────────────
  kv(label: string, value: string | number, valueColor = C.white) {
    this.need(7);
    this.tc(C.gray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8.5);
    this.doc.text(label, this.M + 4, this.y);
    this.tc(valueColor);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8.5);
    this.doc.text(String(value), this.W - this.M - 4, this.y, { align: 'right' });
    // Dotted leader
    this.tc(C.navy3);
    this.doc.setFontSize(8);
    const lw = this.doc.getTextWidth(label + '  ');
    const rw = this.doc.getTextWidth(String(value) + '  ');
    const dots = '· · · · · · · · · · · · · · · · · · · · · · · · · · · · · · · · ·';
    const dotLines = this.doc.splitTextToSize(dots, this.CW - lw - rw - 8);
    this.doc.text(dotLines[0], this.M + 4 + lw, this.y);
    this.y += 6.5;
  }

  // Two-column grid of stat tiles ──────────────────────────────────────────────
  twoCol(items: { label: string; value: string | number; accent?: string }[]) {
    const colW = (this.CW - 3) / 2;
    for (let i = 0; i < items.length; i += 2) {
      this.need(12);
      const row = items.slice(i, i + 2);
      row.forEach((item, j) => {
        const x = this.M + j * (colW + 3);
        this.fill(C.navy2);
        this.doc.roundedRect(x, this.y, colW, 10, 1.5, 1.5, 'F');
        if (item.accent) {
          this.fill(item.accent);
          this.doc.roundedRect(x, this.y, colW, 1.5, 1.5, 0, 'F');
          this.doc.rect(x + colW / 2, this.y, colW / 2, 1.5, 'F');
        }
        this.tc(C.gray);
        this.doc.setFont('helvetica', 'normal');
        this.doc.setFontSize(7);
        this.doc.text(item.label, x + 4, this.y + 5);
        this.tc(item.accent || C.teal);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setFontSize(9);
        this.doc.text(String(item.value), x + colW - 4, this.y + 7.5, { align: 'right' });
      });
      this.y += 12;
    }
  }

  // Cycle timeline row ─────────────────────────────────────────────────────────
  cycleRow(stage: string, value: string | number, ageRange: string, highlight = false) {
    this.need(9);
    if (highlight) { this.fill(C.navy3); this.doc.roundedRect(this.M, this.y - 1, this.CW, 9, 1, 1, 'F'); }
    this.tc(highlight ? C.teal : C.dgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(7.5);
    this.doc.text(stage, this.M + 4, this.y + 4.5);
    this.tc(highlight ? C.white : C.lgray);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8.5);
    this.doc.text(String(value), this.M + 65, this.y + 4.5);
    this.tc(C.dgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(7);
    this.doc.text(ageRange, this.W - this.M - 4, this.y + 4.5, { align: 'right' });
    this.y += 8.5;
  }

  // Body paragraph ─────────────────────────────────────────────────────────────
  body(txt: string, color = C.lgray) {
    this.tc(color);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8.5);
    const lines = this.doc.splitTextToSize(txt, this.CW);
    lines.forEach((line: string) => {
      this.need(6);
      this.doc.text(line, this.M, this.y);
      this.y += 5;
    });
  }

  // Bullet item ────────────────────────────────────────────────────────────────
  bullet(txt: string, dotColor = C.teal) {
    this.need(6);
    this.fill(dotColor);
    this.doc.circle(this.M + 3, this.y - 1, 1, 'F');
    this.tc(C.lgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8.5);
    const lines = this.doc.splitTextToSize(txt, this.CW - 9);
    this.doc.text(lines, this.M + 7, this.y);
    this.y += lines.length * 5 + 0.5;
  }

  // Full interpretation block ──────────────────────────────────────────────────
  interpBlock(label: string, value: string | number, interp: { traits: string[]; challenges: string[]; advice: string[] }) {
    this.need(60);

    // Header band
    this.fill(C.navy2);
    this.doc.roundedRect(this.M, this.y, this.CW, 11, 2, 2, 'F');
    this.fill(C.teal);
    this.doc.roundedRect(this.M, this.y, 3, 11, 2, 0, 'F');
    this.doc.rect(this.M + 1.5, this.y, 1.5, 11, 'F');

    // Number circle
    this.fill(C.teal);
    this.doc.circle(this.M + 14, this.y + 5.5, 5, 'F');
    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.text(String(value), this.M + 14, this.y + 7.2, { align: 'center' });

    this.tc(C.white);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(10);
    this.doc.text(label, this.M + 22, this.y + 7);
    this.y += 14;

    // Traits
    this.tc(C.teal2);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(7.5);
    this.doc.text('KEY TRAITS', this.M + 2, this.y);
    this.y += 5;
    interp.traits.forEach(t => this.bullet(t, C.teal));
    this.y += 2;

    // Challenges
    this.tc(C.gold);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(7.5);
    this.doc.text('CHALLENGES', this.M + 2, this.y);
    this.y += 5;
    interp.challenges.forEach(c => this.bullet(c, C.gold));
    this.y += 2;

    // Advice
    this.tc(C.emerald);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(7.5);
    this.doc.text('GUIDANCE & ADVICE', this.M + 2, this.y);
    this.y += 5;
    interp.advice.forEach(a => this.bullet(a, C.emerald));
    this.y += 6;

    // Divider
    this.stroke(C.navy3);
    this.doc.setLineWidth(0.25);
    this.doc.line(this.M, this.y, this.M + this.CW, this.y);
    this.y += 6;
  }

  // Practitioner notes ─────────────────────────────────────────────────────────
  practitionerBox() {
    this.need(42);
    this.y += 4;
    this.fill(C.navy2);
    this.stroke(C.gold);
    this.doc.setLineWidth(0.4);
    this.doc.roundedRect(this.M, this.y, this.CW, 38, 2, 2, 'FD');
    // Header band
    this.fill(C.gold);
    this.doc.roundedRect(this.M, this.y, this.CW, 8, 2, 2, 'F');
    this.doc.rect(this.M, this.y + 4, this.CW, 4, 'F');
    this.tc(C.navy);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.text('PRACTITIONER NOTES', this.M + 5, this.y + 5.5);
    this.tc(C.navy2);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(7);
    this.doc.text('For private practitioner use — add personalised observations below', this.W - this.M - 3, this.y + 5.5, { align: 'right' });
    this.stroke(C.dgray);
    this.doc.setLineWidth(0.2);
    for (let i = 0; i < 4; i++) {
      const ly = this.y + 15 + i * 6;
      this.doc.line(this.M + 4, ly, this.W - this.M - 4, ly);
    }
    this.y += 44;
  }

  spacer(h = 4) { this.y += h; }

  save(filename: string) {
    const total = this.doc.getNumberOfPages();
    for (let p = 1; p <= total; p++) {
      this.doc.setPage(p);
      if (p > 1) this.pageFooter();
    }
    this.doc.save(filename);
  }

  pageFooter() {
    const fy = this.H - 8;
    this.fill(C.navy);
    this.doc.rect(0, fy - 4, this.W, 14, 'F');
    this.fill(C.teal);
    this.doc.rect(0, fy - 4, 2, 14, 'F');
    this.tc(C.dgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(6);
    this.doc.text(
      `Generated by NumberTeller  ·  www.numberteller.com  ·  ${_today()}`,
      this.W / 2, fy, { align: 'center' }
    );
  }

  // Info box (callout) ─────────────────────────────────────────────────────────
  infoBox(text: string, color = C.teal) {
    this.need(20);
    const lines = this.doc.splitTextToSize(text, this.CW - 14);
    const h = lines.length * 5 + 10;
    this.fill(C.navy2);
    this.doc.roundedRect(this.M, this.y, this.CW, h, 2, 2, 'F');
    this.fill(color);
    this.doc.roundedRect(this.M, this.y, 3, h, 2, 0, 'F');
    this.doc.rect(this.M + 1.5, this.y, 1.5, h, 'F');
    this.tc(color);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(7);
    this.doc.text('NOTE', this.M + 7, this.y + 5.5);
    this.tc(C.lgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.text(lines, this.M + 7, this.y + 11);
    this.y += h + 4;
  }

  // Table of contents entry ────────────────────────────────────────────────────
  tocEntry(num: string, title: string, page: number) {
    this.need(8);
    this.tc(C.teal);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.text(num, this.M + 4, this.y);
    this.tc(C.lgray);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.text(title, this.M + 14, this.y);
    this.tc(C.dgray);
    this.doc.text(String(page), this.W - this.M - 4, this.y, { align: 'right' });
    this.stroke(C.navy3);
    this.doc.setLineWidth(0.15);
    const textEnd = this.M + 14 + this.doc.getTextWidth(title) + 3;
    this.doc.line(textEnd, this.y - 0.5, this.W - this.M - 12, this.y - 0.5);
    this.y += 8;
  }
}

// ─── Utilities ────────────────────────────────────────────────────────────────
function _today(): string {
  return new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
}

function numVal(v: string | number): number {
  if (typeof v === 'number') return v;
  const parts = String(v).split('/');
  return parseInt(parts[parts.length - 1]) || parseInt(parts[0]) || 0;
}

function planLabel(planId: string): string {
  if (planId === 'expert') return 'Expert Plan';
  if (planId === 'calculator') return 'Calculator Plan';
  return 'Free Trial';
}

const PY_THEMES: Record<number, { title: string; desc: string }> = {
  1: { title: 'New Beginnings', desc: 'A year of fresh starts, bold initiatives, and leadership. Plant the seeds you wish to harvest over the coming 9-year cycle.' },
  2: { title: 'Partnership & Patience', desc: 'A year for building alliances, deepening relationships, and practising diplomacy. Collaboration yields greater results than solo effort.' },
  3: { title: 'Creative Expression', desc: 'Communication, creativity, and social expansion are highlighted. Share your voice, embrace joy, and pursue artistic endeavours.' },
  4: { title: 'Foundation Building', desc: 'A year of practical work, structure, and discipline. Lay the groundwork for lasting achievement through steady, focused effort.' },
  5: { title: 'Change & Freedom', desc: 'Expect significant change, travel, and unexpected opportunity. Stay adaptable. This is a year of dynamic movement and variety.' },
  6: { title: 'Responsibility & Service', desc: 'Home, family, and community are the focus. Take on responsibilities gracefully and offer service — deep fulfilment follows.' },
  7: { title: 'Introspection & Wisdom', desc: 'A year for inner development, study, and spiritual deepening. Solitude is valuable; seek answers within before looking outward.' },
  8: { title: 'Power & Achievement', desc: 'Material ambitions, financial growth, and leadership opportunities abound. Take charge, act decisively, and claim your authority.' },
  9: { title: 'Completion & Release', desc: 'A cycle closes. Release what no longer serves you — relationships, projects, or beliefs. Make space for the new cycle ahead.' },
};

// ─── Core Chart PDF ───────────────────────────────────────────────────────────
export function exportToPDF(results: any, planId = 'free') {
  const fullContent = planId === 'expert' || planId === 'free'; // free trial and expert get full interpretations
  const pdf = new PDF(planId);

  const birthStr = results.birthDate instanceof Date
    ? results.birthDate.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : String(results.birthDate ?? '');

  const coverNumbers = [
    { label: 'Life Path', value: results.coreNumbers.lifePath },
    { label: 'Expression', value: results.coreNumbers.expression },
    { label: 'Soul Urge', value: results.coreNumbers.soulUrge },
    { label: 'Personality', value: results.coreNumbers.personality },
    { label: 'Birthday', value: results.coreNumbers.birthday },
    { label: 'Personal Year', value: results.cycles?.personalYear ?? '' },
  ];

  // ── Cover ──
  pdf.cover(results.fullName, birthStr, planLabel(planId), coverNumbers);

  // ── Page 2: Core Numbers ──
  pdf.doc.addPage();
  pdf.page = 1;
  pdf._pageChrome();
  pdf.y = 26;

  pdf.sectionHeading('1. Core Numbers', C.teal);
  pdf.body('Your core numbers form the foundation of your numerological profile. Derived from your full birth name and date of birth, they reveal your life purpose, the way you express yourself, and your deepest inner motivations.', C.gray);
  pdf.spacer(4);

  const coreEntries = [
    { label: 'Life Path Number', value: results.coreNumbers.lifePath },
    { label: 'Expression Number', value: results.coreNumbers.expression },
    { label: 'Soul Urge Number', value: results.coreNumbers.soulUrge },
    { label: 'Personality Number', value: results.coreNumbers.personality },
    { label: 'Birthday Number', value: results.coreNumbers.birthday },
    { label: 'Maturity Number', value: results.coreNumbers.maturity },
    { label: 'Attitude Number', value: results.coreNumbers.attitude },
    { label: 'Rational Thought Number', value: results.coreNumbers.rationalThought },
  ];

  coreEntries.forEach(({ label, value }) => {
    const interp = fullContent ? NUMBER_INTERPRETATIONS[numVal(value)] : undefined;
    pdf.numberCard(label, value, interp);
  });

  // ── Page 3: Life Cycles ──
  pdf.newPage();
  pdf.sectionHeading('2. Life Cycles & Timing', C.teal);
  pdf.body('Numerology unfolds in cycles. Your Personal Year reveals the energy and themes active in the current year, while your Period Cycles, Pinnacles, and Challenges map the longer arc of your development.', C.gray);
  pdf.spacer(4);

  // Current timing grid
  pdf.twoCol([
    { label: 'Personal Year', value: results.cycles.personalYear, accent: C.teal },
    { label: 'Universal Year', value: results.cycles.universalYear, accent: C.dgray },
    { label: 'Essence Number', value: results.cycles.essence, accent: C.gold },
    { label: 'Current Year', value: new Date().getFullYear(), accent: C.dgray },
  ]);
  pdf.spacer(4);

  // Personal Year deep-dive
  const py = numVal(results.cycles.personalYear);
  const pyTheme = PY_THEMES[py];
  if (pyTheme) {
    pdf.need(28);
    pdf.fill(C.navy2);
    pdf.doc.roundedRect(pdf.M, pdf.y, pdf.CW, 26, 2, 2, 'F');
    pdf.fill(C.teal);
    pdf.doc.roundedRect(pdf.M, pdf.y, 3, 26, 2, 0, 'F');
    pdf.doc.rect(pdf.M + 1.5, pdf.y, 1.5, 26, 'F');
    pdf.tc(C.teal2);
    pdf.doc.setFont('helvetica', 'bold');
    pdf.doc.setFontSize(7.5);
    pdf.doc.text(`PERSONAL YEAR ${py}`, pdf.M + 7, pdf.y + 7);
    pdf.tc(C.white);
    pdf.doc.setFont('helvetica', 'bold');
    pdf.doc.setFontSize(10);
    pdf.doc.text(pyTheme.title, pdf.M + 7, pdf.y + 13);
    pdf.tc(C.lgray);
    pdf.doc.setFont('helvetica', 'normal');
    pdf.doc.setFontSize(8);
    const pyLines = pdf.doc.splitTextToSize(pyTheme.desc, pdf.CW - 12);
    pdf.doc.text(pyLines, pdf.M + 7, pdf.y + 19);
    pdf.y += 29;
  }

  pdf.spacer(2);
  pdf.subHeading('Period Cycles (Life Sections)');
  const pc = results.cycles.periodCycles;
  if (pc) {
    pdf.cycleRow('First Period', pc.first.value, `Ages ${pc.first.ageRange}`);
    pdf.cycleRow('Second Period', pc.second.value, `Ages ${pc.second.ageRange}`);
    pdf.cycleRow('Third Period', pc.third.value, `Ages ${pc.third.ageRange}`);
  }
  pdf.spacer(4);

  pdf.subHeading('Pinnacle Numbers');
  const pin = results.cycles.pinnacles;
  if (pin) {
    pdf.cycleRow('First Pinnacle', pin.first.value, `Ages ${pin.first.ageRange}`);
    pdf.cycleRow('Second Pinnacle', pin.second.value, `Ages ${pin.second.ageRange}`);
    pdf.cycleRow('Third Pinnacle', pin.third.value, `Ages ${pin.third.ageRange}`);
    pdf.cycleRow('Fourth Pinnacle', pin.fourth.value, `Ages ${pin.fourth.ageRange}`, true);
  }
  pdf.spacer(4);

  pdf.subHeading('Challenge Numbers');
  const ch = results.cycles.challenges;
  if (ch) {
    pdf.cycleRow('First Challenge', ch.first.value, `Ages ${ch.first.ageRange}`);
    pdf.cycleRow('Second Challenge', ch.second.value, `Ages ${ch.second.ageRange}`);
    pdf.cycleRow('Third Challenge', ch.third.value, `Ages ${ch.third.ageRange}`);
    pdf.cycleRow('Main Challenge', ch.fourth.value, 'Lifelong', true);
  }

  // ── Page 4: Karmic & Personal Details ──
  pdf.newPage();
  pdf.sectionHeading('3. Karmic Patterns', C.rose);
  pdf.body('Karmic lessons reflect the numbers missing from your birth name, indicating qualities that require development in this lifetime. Karmic debt numbers carry a heavier lesson from past-life patterns.', C.gray);
  pdf.spacer(4);

  const karmic = results.karmic;
  if (karmic) {
    const lessons = karmic.lessons?.length
      ? karmic.lessons.map((l: any) => `${l.number}${l.modified ? ' (Modified)' : ''}`).join(', ')
      : 'None — all numbers are present in your name.';
    pdf.kv('Karmic Lessons', lessons);
    pdf.kv('Prime Intensifier', karmic.primeIntensifier ?? 'None');
  }

  pdf.spacer(6);
  pdf.sectionHeading('4. Additional Details', C.gold);
  const det = results.details;
  if (det) {
    pdf.kv('Ruling Planet', det.rulingPlanet ?? '');
    pdf.kv('Harmony Numbers', det.harmonyNumbers?.join(', ') ?? '');
    pdf.kv('Favourable Colours', det.favourableColours?.join(', ') ?? '');
    pdf.kv('Zodiac Sign', det.zodiac ? `${det.zodiac.sign} (${det.zodiac.element})` : '');
    pdf.kv('First Letter', det.firstLetter ? `${det.firstLetter.letter} = ${det.firstLetter.value}` : '');
    pdf.kv('First Vowel', det.firstVowel ? `${det.firstVowel.letter} = ${det.firstVowel.value}` : '');
  }

  // Lo Shu summary
  if (results.loshuGrid) {
    pdf.spacer(6);
    pdf.sectionHeading('5. Lo Shu Grid Summary', C.teal);
    pdf.kv('Missing Numbers', results.loshuGrid.missingNumbers?.join(', ') || 'None');
    pdf.kv('Active Arrows', results.loshuGrid.arrows?.join(', ') || 'None');
  }

  // ── Page 5+: Full Interpretations (Expert / Free Trial) ──
  if (fullContent) {
    pdf.newPage();
    pdf.sectionHeading('6. Detailed Number Interpretations', C.teal);
    pdf.body('Each core number below is interpreted in depth — its gifts, its challenges, and specific guidance for working with that energy consciously.', C.gray);
    pdf.spacer(6);

    const interpEntries = [
      { label: 'Life Path Number', value: results.coreNumbers.lifePath },
      { label: 'Expression Number', value: results.coreNumbers.expression },
      { label: 'Soul Urge Number', value: results.coreNumbers.soulUrge },
      { label: 'Personality Number', value: results.coreNumbers.personality },
    ];

    interpEntries.forEach(({ label, value }) => {
      const interp = NUMBER_INTERPRETATIONS[numVal(value)];
      if (!interp) return;
      pdf.interpBlock(label, value, interp);
    });

    // Closing guidance
    pdf.newPage();
    pdf.sectionHeading('7. Putting It All Together', C.emerald);
    pdf.body(`This reading is a tool for self-understanding, not a fixed destiny. The numbers reveal the energies and themes present in your life — how you work with them is always your choice.`, C.gray);
    pdf.spacer(4);
    pdf.infoBox(`Your Life Path ${results.coreNumbers.lifePath} is your primary energy — the river you are always flowing in. Your Expression ${results.coreNumbers.expression} is how the world sees you manifest it. Your Soul Urge ${results.coreNumbers.soulUrge} is your inner compass that guides which opportunities feel aligned. When these three numbers work in harmony, life tends to feel effortless and purposeful.`, C.teal);
    pdf.spacer(4);
    pdf.body('Dates and cycles to watch in the coming year:', C.lgray);
    pdf.spacer(2);
    pdf.bullet(`Personal Year ${results.cycles.personalYear}: ${PY_THEMES[numVal(results.cycles.personalYear)]?.desc ?? ''}`);
    pdf.bullet(`Essence ${results.cycles.essence} runs through the current year, shaping the texture of daily events.`);
    pdf.spacer(4);
    pdf.practitionerBox();
  }

  const safeName = results.fullName?.replace(/\s+/g, '-') ?? 'Chart';
  pdf.save(`NumberTeller-${safeName}-${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Lo Shu Grid PDF ─────────────────────────────────────────────────────────
export function exportLoShuGridToPDF(results: any, planId = 'free') {
  const fullContent = planId === 'expert' || planId === 'free';
  const pdf = new PDF(planId);

  pdf.cover(
    results.name,
    results.dateOfBirth,
    planLabel(planId),
    [
      { label: 'Driver', value: results.driverNumber },
      { label: 'Conductor', value: results.conductorNumber },
      { label: 'Kua Number', value: results.kuaNumber },
      { label: 'Missing', value: results.missingNumbers?.length || 0 },
      { label: 'Arrows', value: results.arrows?.length || 0 },
    ]
  );

  // ── Page 2: Subject & Grid ──
  pdf.doc.addPage();
  pdf.page = 1;
  pdf._pageChrome();
  pdf.y = 26;

  pdf.sectionHeading('1. Subject Overview', C.teal);
  pdf.kv('Full Name', results.name);
  pdf.kv('Date of Birth', results.dateOfBirth);
  pdf.kv('Gender', results.gender);
  pdf.spacer(4);

  pdf.sectionHeading('2. Key Numbers', C.teal);
  pdf.twoCol([
    { label: 'Driver Number', value: results.driverNumber, accent: C.teal },
    { label: 'Conductor Number', value: results.conductorNumber, accent: C.gold },
    { label: 'Kua Number', value: results.kuaNumber, accent: C.emerald },
    { label: 'Missing Numbers', value: results.missingNumbers?.length || 0, accent: C.rose },
  ]);
  pdf.spacer(6);

  // ── Lo Shu Grid Visual ──
  pdf.sectionHeading('3. Lo Shu Grid', C.teal);
  pdf.body('The Lo Shu grid maps the digits of your birth date into a 3×3 magic square. The presence or absence of numbers, and the patterns they form (arrows), reveal strengths, challenges, and unique talents.', C.gray);
  pdf.spacer(4);

  const CS = 22; // cell size
  const GAP = 2;
  const gridW = 3 * CS + 2 * GAP;
  const gridX = pdf.M + (pdf.CW - gridW) / 2;
  const gridY = pdf.y;
  const gridNums = [[4, 9, 2], [3, 5, 7], [8, 1, 6]];
  const planeColors: Record<number, string> = { 4: C.teal, 9: C.teal, 2: C.teal, 3: C.gold, 5: C.white, 7: C.gold, 8: C.rose, 1: C.rose, 6: C.rose };

  for (let row = 0; row < 3; row++) {
    for (let col = 0; col < 3; col++) {
      const cx = gridX + col * (CS + GAP);
      const cy = gridY + row * (CS + GAP);
      const cellNum = gridNums[row][col];
      const cellData = results.grid?.[row]?.[col];
      const digits: number[] = Array.isArray(cellData) ? cellData : [];
      const isEmpty = digits.length === 0;

      // Cell background
      pdf.fill(isEmpty ? C.navy2 : C.navy3);
      pdf.stroke(isEmpty ? C.dgray : planeColors[cellNum] || C.teal);
      pdf.doc.setLineWidth(0.5);
      pdf.doc.roundedRect(cx, cy, CS, CS, 2, 2, 'FD');

      // Cell position number (small, top-left corner)
      pdf.tc(isEmpty ? C.dgray : C.dgray);
      pdf.doc.setFont('helvetica', 'normal');
      pdf.doc.setFontSize(5.5);
      pdf.doc.text(String(cellNum), cx + 2, cy + 4.5);

      if (!isEmpty) {
        pdf.tc(C.white);
        pdf.doc.setFont('helvetica', 'bold');
        pdf.doc.setFontSize(digits.length >= 3 ? 8 : 11);
        const digStr = digits.join('  ');
        pdf.doc.text(digStr, cx + CS / 2, cy + CS / 2 + 3, { align: 'center' });
      } else {
        pdf.tc(C.dgray);
        pdf.doc.setFont('helvetica', 'bold');
        pdf.doc.setFontSize(16);
        pdf.doc.text('—', cx + CS / 2, cy + CS / 2 + 3, { align: 'center' });
      }
    }
  }
  pdf.y = gridY + 3 * (CS + GAP) + 6;

  // Grid legend
  pdf.need(10);
  pdf.tc(C.gray);
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(7);
  const legend = [
    { label: 'Mental Plane', color: C.teal },
    { label: 'Emotional Plane', color: C.gold },
    { label: 'Practical Plane', color: C.rose },
  ];
  let lx = gridX;
  legend.forEach(l => {
    pdf.fill(l.color);
    pdf.doc.circle(lx + 2, pdf.y + 2, 1.5, 'F');
    pdf.tc(C.gray);
    pdf.doc.setFontSize(7);
    pdf.doc.text(l.label, lx + 5.5, pdf.y + 3.5);
    lx += 45;
  });
  pdf.y += 8;

  // Number counts
  pdf.spacer(4);
  pdf.sectionHeading('4. Number Frequency', C.gold);
  const countItems: { label: string; value: string | number; accent?: string }[] = [];
  Object.entries(results.numberCounts as Record<string, number>).forEach(([num, count]) => {
    countItems.push({ label: `Number ${num}`, value: `${count}×`, accent: Number(count) >= 3 ? C.gold : C.dgray });
  });
  pdf.twoCol(countItems);

  // ── Page 3: Missing Numbers ──
  if (results.missingNumbers?.length > 0) {
    pdf.newPage();
    pdf.sectionHeading('5. Missing Numbers & Remedies', C.rose);
    pdf.body('Numbers absent from your birth date represent qualities that may need conscious cultivation. The remedies below help balance these energies in your daily environment and practice.', C.gray);
    pdf.spacer(4);

    results.missingNumbers.forEach((num: number) => {
      const remedy = MISSING_NUMBER_REMEDIES[num as keyof typeof MISSING_NUMBER_REMEDIES];
      if (!remedy) return;
      pdf.need(40);
      pdf.subHeading(`Missing ${num} — ${remedy.element} Element`, C.rose);
      pdf.body('Potential weaknesses this gap may create:', C.gray);
      remedy.weaknesses.forEach((w: string) => pdf.bullet(w, C.rose));
      pdf.spacer(2);
      if (fullContent) {
        pdf.body('Recommended remedies:', C.gray);
        remedy.remedies.forEach((r: string) => pdf.bullet(r, C.emerald));
      }
      pdf.spacer(5);
    });
  }

  // Arrows
  if (results.arrows?.length > 0) {
    pdf.spacer(2);
    pdf.sectionHeading('6. Arrows & Special Patterns', C.teal);
    pdf.body('Arrows are lines of three numbers aligned in the grid. Their presence indicates intensified traits; their absence reveals areas for growth.', C.gray);
    pdf.spacer(3);
    results.arrows.forEach((arrow: string) => pdf.bullet(arrow, C.teal));
  }

  // Planes
  pdf.spacer(4);
  pdf.sectionHeading('7. Planes of Expression', C.gold);
  const planes = results.planes;
  if (planes) {
    if (planes.mental) pdf.kv('Mental Plane', planes.mental.strength, C.teal);
    if (planes.emotional) pdf.kv('Emotional Plane', planes.emotional.strength, C.gold);
    if (planes.practical) pdf.kv('Practical Plane', planes.practical.strength, C.rose);
    if (planes.intuitive) pdf.kv('Intuitive Plane', planes.intuitive.strength, C.emerald);
  }

  // Five Elements — full content
  if (fullContent) {
    pdf.newPage();
    pdf.sectionHeading('8. Five Elements Cycle & Remedies', C.emerald);
    pdf.body('The Five Elements — Water, Wood, Fire, Earth, and Metal — form the foundation of Chinese metaphysics. Each element interacts through productive and destructive cycles. Balancing these energies in your environment, diet, and daily rhythm supports harmony and vitality.', C.gray);
    pdf.spacer(6);

    Object.entries(ELEMENT_REMEDIES).forEach(([, element]) => {
      pdf.need(40);
      pdf.subHeading(`${element.element} Element`, C.emerald);
      pdf.kv('Enhanced by', element.enhanceWith.join(', '));
      pdf.kv('Weakened by', element.weakenedBy.join(', '));
      pdf.spacer(2);
      element.remedies.slice(0, 4).forEach((r: string) => pdf.bullet(r, C.emerald));
      pdf.spacer(5);
    });

    pdf.practitionerBox();
  }

  const safeName = results.name?.replace(/\s+/g, '-') ?? 'LoShu';
  pdf.save(`NumberTeller-LoShu-${safeName}-${new Date().toISOString().split('T')[0]}.pdf`);
}
