import { MISSING_NUMBER_REMEDIES, ELEMENT_REMEDIES } from '../data/loShuInterpretations';

export function exportToPDF(results: any) {
  const content = `
NUMEROLOGY READING
==================

Full Name: ${results.fullName}
Birth Date: ${results.birthDate.toLocaleDateString()}
Current Year: ${results.currentYear}

CORE NUMBERS
------------
Life Path Number: ${results.coreNumbers.lifePath}
Expression Number: ${results.coreNumbers.expression}
Soul Urge Number: ${results.coreNumbers.soulUrge}
Personality Number: ${results.coreNumbers.personality}
Birthday Number: ${results.coreNumbers.birthday}
Maturity Number: ${results.coreNumbers.maturity}
Attitude Number: ${results.coreNumbers.attitude}
Rational Thought Number: ${results.coreNumbers.rationalThought}

CYCLES
------
Personal Year: ${results.cycles.personalYear}
Universal Year: ${results.cycles.universalYear}
Essence Number: ${results.cycles.essence}

Period Cycles:
  First Period: ${results.cycles.periodCycles.first.value} (Age ${results.cycles.periodCycles.first.ageRange})
  Second Period: ${results.cycles.periodCycles.second.value} (Age ${results.cycles.periodCycles.second.ageRange})
  Third Period: ${results.cycles.periodCycles.third.value} (Age ${results.cycles.periodCycles.third.ageRange})

Pinnacles:
  First: ${results.cycles.pinnacles.first.value} (Age ${results.cycles.pinnacles.first.ageRange})
  Second: ${results.cycles.pinnacles.second.value} (Age ${results.cycles.pinnacles.second.ageRange})
  Third: ${results.cycles.pinnacles.third.value} (Age ${results.cycles.pinnacles.third.ageRange})
  Fourth: ${results.cycles.pinnacles.fourth.value} (Age ${results.cycles.pinnacles.fourth.ageRange})

Challenges:
  First: ${results.cycles.challenges.first.value} (Age ${results.cycles.challenges.first.ageRange})
  Second: ${results.cycles.challenges.second.value} (Age ${results.cycles.challenges.second.ageRange})
  Third: ${results.cycles.challenges.third.value} (Age ${results.cycles.challenges.third.ageRange})
  Fourth: ${results.cycles.challenges.fourth.value} (Age ${results.cycles.challenges.fourth.ageRange})

KARMIC INSIGHTS
---------------
Karmic Lessons: ${results.karmic.lessons.map((l: any) => `${l.number}${l.modified ? ' (Modified)' : ''}`).join(', ') || 'None'}
Prime Intensifier: ${results.karmic.primeIntensifier}

ADDITIONAL DETAILS
------------------
Ruling Planet: ${results.details.rulingPlanet}
Harmony Numbers: ${results.details.harmonyNumbers.join(', ')}
Favourable Colours: ${results.details.favourableColours.join(', ')}
Zodiac Sign: ${results.details.zodiac.sign} (${results.details.zodiac.element})
First Letter: ${results.details.firstLetter.letter} = ${results.details.firstLetter.value}
First Vowel: ${results.details.firstVowel.letter} = ${results.details.firstVowel.value}

LOSHU GRID
----------
${results.loshuGrid.grid.map((row: any[]) => row.map(cell => cell || '0').join(' | ')).join('\n')}

Missing Numbers: ${results.loshuGrid.missingNumbers.join(', ') || 'None'}
Active Arrows: ${results.loshuGrid.arrows.join(', ') || 'None'}

---
Generated by NumberTeller - www.numberteller.com
  `.trim();

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `numerology-reading-${results.fullName.replace(/\s+/g, '-').toLowerCase()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportLoShuGridToPDF(results: any) {
  let content = `
LO SHU GRID NUMEROLOGY READING
===============================

Name: ${results.name}
Date of Birth: ${results.dateOfBirth}
Gender: ${results.gender}

LO SHU GRID
-----------
${results.grid.map((row: any[]) =>
  row.map(cell => {
    if (Array.isArray(cell) && cell.length > 0) {
      return cell.join(',');
    }
    return '-';
  }).join('  |  ')
).join('\n')}

KEY NUMBERS
-----------
Driver Number: ${results.driverNumber}
Conductor Number: ${results.conductorNumber}
Kua Number: ${results.kuaNumber}

NUMBER ANALYSIS
---------------
`;

  Object.entries(results.numberCounts).forEach(([num, count]) => {
    content += `Number ${num}: Appears ${count} time(s)\n`;
  });

  if (results.missingNumbers.length > 0) {
    content += `\nMISSING NUMBERS & REMEDIES\n`;
    content += `==========================\n\n`;

    results.missingNumbers.forEach((num: number) => {
      const remedy = MISSING_NUMBER_REMEDIES[num as keyof typeof MISSING_NUMBER_REMEDIES];
      if (remedy) {
        content += `Missing Number ${num} - ${remedy.element}\n`;
        content += `${'='.repeat(40)}\n\n`;
        content += `Potential Weaknesses:\n`;
        remedy.weaknesses.forEach((weakness: string) => {
          content += `  • ${weakness}\n`;
        });
        content += `\nRemedies:\n`;
        remedy.remedies.forEach((r: string) => {
          content += `  • ${r}\n`;
        });
        content += `\n`;
      }
    });
  }

  if (results.repeatingNumbers.length > 0) {
    content += `\nREPEATING NUMBERS\n`;
    content += `=================\n\n`;
    results.repeatingNumbers.forEach((item: any) => {
      content += `Number ${item.number}: Repeats ${item.count} times\n`;
    });
    content += `\n`;
  }

  content += `\nPLANES OF EXPRESSION\n`;
  content += `====================\n\n`;

  if (results.planes.mental) {
    content += `Mental Plane: ${results.planes.mental.strength}\n`;
  }
  if (results.planes.emotional) {
    content += `Emotional Plane: ${results.planes.emotional.strength}\n`;
  }
  if (results.planes.practical) {
    content += `Practical Plane: ${results.planes.practical.strength}\n`;
  }
  if (results.planes.intuitive) {
    content += `Intuitive Plane: ${results.planes.intuitive.strength}\n`;
  }

  if (results.arrows && results.arrows.length > 0) {
    content += `\nARROWS (SPECIAL PATTERNS)\n`;
    content += `=========================\n\n`;
    results.arrows.forEach((arrow: string) => {
      content += `• ${arrow}\n`;
    });
    content += `\n`;
  }

  content += `\nFIVE ELEMENTS CYCLE & REMEDIES\n`;
  content += `==============================\n\n`;
  content += `The Five Elements (Water, Wood, Fire, Earth, Metal) interact in three cycles:\n\n`;
  content += `1. PRODUCTIVE CYCLE (Creates/Nourishes):\n`;
  content += `   Water → Wood → Fire → Earth → Metal → Water\n\n`;
  content += `2. EXHAUSTIVE CYCLE (Weakens):\n`;
  content += `   The reverse of productive cycle\n\n`;
  content += `3. DESTRUCTIVE CYCLE (Controls):\n`;
  content += `   Water → Fire, Fire → Metal, Metal → Wood, Wood → Earth, Earth → Water\n\n`;

  Object.entries(ELEMENT_REMEDIES).forEach(([key, element]) => {
    content += `${element.element.toUpperCase()} ELEMENT\n`;
    content += `${'='.repeat(40)}\n`;
    content += `Enhance with: ${element.enhanceWith.join(', ')}\n`;
    content += `Weakened by: ${element.weakenedBy.join(', ')}\n\n`;
    content += `Remedies:\n`;
    element.remedies.forEach((remedy: string) => {
      content += `  • ${remedy}\n`;
    });
    content += `\n`;
  });

  content += `\nGENERAL RECOMMENDATIONS\n`;
  content += `=======================\n\n`;
  content += `1. Balance is Key: No element should be too strong or too weak\n`;
  content += `2. Use the Productive Cycle to strengthen weak elements\n`;
  content += `3. Use the Exhaustive Cycle to reduce overly strong elements\n`;
  content += `4. Avoid Destructive Cycle interactions in your environment\n`;
  content += `5. Regularly assess and adjust your space based on life changes\n\n`;

  content += `\n---\n`;
  content += `Generated by NumberTeller - Your Personal Numerology Guide\n`;
  content += `Date: ${new Date().toLocaleDateString()}\n`;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `loshu-grid-${results.name.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
